#
# Blog Settings
#
author: Kyle Neumeier
description: A jouryney to uncommon
url: http://towardsuncommon.com
title: Towards Uncommon
subtitle: The web log detailing the journey of an ordinary software developer
gravatar_url: http://www.gravatar.com/avatar/a5ace0638f020717d2ededf10fdae506
#subscribe_rss: http://feeds.haacked.com/haacked

# Github repositories
github_user: kneumei
github_repo_url: https://github.com/kneumei/haacked.com/

# Twitter
twitter_user: kneumei
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: towardsuncommon
disqus_show_comment_count: true

# Google Analytics
#google_analytics_tracking_id: UA-177588-1


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
